export const GET_PROFILE_TEACHER = "GET_PROFILE_TEACHER";
export const GET_STUDENTS_LIST = "GET_STUDENTS_LIST";
export const PUT_STUDENT_APPROVE = "PUT_STUDENT_APPROVE";
export const POST_STUDENT_INVITE = "POST_STUDENT_INVITE";
export const SEARCH_STUDENT = "SEARCH_STUDENT";
export const FETCH_LOADING = "FETCH_LOADING"
export const FETCH_ACCEPT_LOADING = "FETCH_ACCEPT_LOADING"
